-- Home inbox: deterministic recurring reminders + rule-driven items (backlog §9).

create table public.home_inbox_items (
  id uuid primary key default gen_random_uuid(),
  owner_id uuid not null references auth.users (id) on delete cascade,
  rule_key text not null,
  dedupe_key text not null,
  title text not null,
  body text,
  link_path text,
  status text not null default 'open' check (status in ('open', 'done')),
  created_at timestamptz not null default now(),
  resolved_at timestamptz,
  metadata jsonb,
  constraint home_inbox_items_owner_dedupe unique (owner_id, dedupe_key)
);

comment on table public.home_inbox_items is
  'User-scoped Home inbox items generated by recurring rules; idempotent via (owner_id, dedupe_key).';

create index home_inbox_items_owner_status_idx
  on public.home_inbox_items (owner_id, status, created_at desc);

alter table public.home_inbox_items enable row level security;

create policy "home_inbox_items_owner"
  on public.home_inbox_items
  for all
  using (owner_id = auth.uid())
  with check (owner_id = auth.uid());
